### ISSUE TITLE
How can I do the same for myself?

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [thesadru/genshin-stats#1]
I tried to figure out how I could make it automatically display as well, but I'm not quite sure how. is it enough just to change the values in .py, or something else?

**Comment by ashleney** [comment]
No need to change anything, all you need to do is clone and set an environment variable with your cookies.
![image](https://user-images.githubusercontent.com/58166507/231578177-4366644a-1869-4474-b8ef-c96c2af8d42c.png)

(I would probably recommend using a different template though)

**Comment by MIPOHBOPOHIH** [comment]
I'm sorry, but what exactly should I write in COOKIES? will it automatically update the README.md. or what do I have to do to do this?

**Comment by ashleney** [comment]
The cookie headers sent to the hoyolab API. Refer to genshin.py docs.
